name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    name: Build
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Show current version of Xcode
      run: xcodebuild -version
    - name: Build optool
      run: xcodebuild -scheme optool build -configuration Release
    - name: Build release tar.gz
      run: |
        mkdir ./release
        cd release
        find ~/Library/Developer/Xcode/DerivedData/optool*/Build/Products/Release -type f -depth 1 -iname "optool" -exec cp {} ./ \;
        tar -cvzf optool.tar.gz optool
    - name: Store Archive
      uses: actions/upload-artifact@v4
      with:
        name: optool
        path: release/optool.tar.gz